name: Lint

on:
  pull_request:
    branches: [releases]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.test.txt
          pip install -r requirements.dev.txt

      - name: Run isort --check
        run: |
          isort --check custom_components/ics_calendar tests

      - name: Run black --check
        run: |
          black --check custom_components/ics_calendar tests

      - name: Run flake8
        run: |
          flake8

      - name: Run pydocstyle
        run: |
          pydocstyle -v custom_components/ics_calendar tests

      - name: Run pylint
        run: |
          pylint custom_components/ics_calendar
